In [36]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
ITAI 3375 Lab 10 Midterm Project: Full-Stack Data Curation Dataset: NYC 311 Service Requests from 2020 to Present
</h1>
"""))

# ITAI 3375 Lab 10 Midterm Project
# Full-Stack Data Curation

# Dataset: NYC 311 Service Requests from 2020 to Present

# Step 1: Dataset

For this project, I chose the NYC 311 Service Requests from 2020 to Present dataset. This dataset is published by NYC Open Data and is also available through public open-government data sources. It contains public service requests submitted by residents, including complaints about noise, illegal parking, sanitation, housing conditions, street issues, damaged trees, heat/hot water problems, and other city service concerns. The dataset meets the assignment requirement because it has far more than 500 rows and can be opened in Python as a CSV file using pandas. The data is public open-government data, so it can be used for educational and analysis purposes. An AI use case for this dataset is classification, where a model could learn to predict the urgency level of a service request, the responsible city agency, or the type of complaint based on the complaint description and related fields. One quality problem I noticed is that the dataset has missing values in fields such as closed date, descriptor, incident ZIP, city, latitude, and longitude. It also contains inconsistent formats in date fields and some incomplete location information, which makes it useful for practicing data cleaning and curation.

# Step 2a: Load and Count

In [37]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 2a: Load and Count
</h1>
"""))

In [11]:
import pandas as pd
import numpy as np
from urllib.parse import urlencode

base_url = "https://data.cityofnewyork.us/resource/erm2-nwe9.csv"

params = {
    "$limit": 1000000,
    "$select": "unique_key,created_date,closed_date,agency,complaint_type,descriptor,incident_zip,city,status,borough,latitude,longitude"
}

url = base_url + "?" + urlencode(params)

df = pd.read_csv(url)

print("Rows before cleaning:", df.shape[0])
print("Columns before cleaning:", df.shape[1])
df.head()

Rows before cleaning: 1000000
Columns before cleaning: 12

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,incident_zip,city,status,borough,latitude,longitude
0,69639237,2026-07-08T02:11:18.000,NaN,DOT,Street Condition,Pothole,11378.0,QUEENS,Open,QUEENS,NaN,NaN
1,69639521,2026-07-08T01:51:01.000,NaN,NYPD,Noise - Residential,Loud Music/Party,11421.0,WOODHAVEN,In Progress,QUEENS,40.694519,-73.865851
2,69634788,2026-07-08T01:50:16.000,NaN,NYPD,Noise - Residential,Banging/Pounding,11208.0,BROOKLYN,In Progress,BROOKLYN,40.672453,-73.879446
3,69642732,2026-07-08T01:50:02.000,NaN,NYPD,Illegal Parking,Blocked Hydrant,11420.0,SOUTH OZONE PARK,In Progress,QUEENS,40.676386,-73.812307
4,69641154,2026-07-08T01:49:41.000,NaN,NYPD,Noise - Street/Sidewalk,Loud Talking,10002.0,NEW YORK,In Progress,MANHATTAN,40.722091,-73.985804

# Step 2b: Profile the Data

In [38]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 2: Profile the Data
</h1>
"""))

In [12]:
df.info()
df.describe(include="all")
print("Missing values in each column:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique values in each column:")
print(df.nunique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   unique_key      1000000 non-null  int64
 1   created_date    1000000 non-null  object
 2   closed_date     908281 non-null   object
 3   agency          1000000 non-null  object
 4   complaint_type  1000000 non-null  object
 5   descriptor      973886 non-null   object
 6   incident_zip    991296 non-null   float64
 7   city            942093 non-null   object
 8   status          1000000 non-null  object
 9   borough         1000000 non-null  object
 10  latitude        975793 non-null   float64
 11  longitude       975793 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 91.6+ MB
Missing values in each column:
unique_key            0
created_date          0
closed_date       91719
agency                0
complaint_type        0
descriptor        26114
incident_zip       8704
city              57907
status                0
borough               0
latitude          24207
longitude         24207
dtype: int64

Duplicate rows:
0

Unique values in each column:
unique_key        1000000
created_date       826307
closed_date        664572
agency                 15
complaint_type        183
descriptor            862
incident_zip          270
city                   94
status                  7
borough                 6
latitude           283186
longitude          283185
dtype: int64

# Step 2c: Fixing Two Problems

In [39]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 2a:Fixing Two Problems
</h1>
"""))

In [13]:
df_clean = df.copy()

# Fix 1: Fill missing values in important category/text columns
df_clean["descriptor"] = df_clean["descriptor"].fillna("Unknown")
df_clean["city"] = df_clean["city"].fillna("Unknown")
df_clean["incident_zip"] = df_clean["incident_zip"].fillna("Unknown")

# Fix 2: Standardize date columns
df_clean["created_date"] = pd.to_datetime(df_clean["created_date"], errors="coerce")
df_clean["closed_date"] = pd.to_datetime(df_clean["closed_date"], errors="coerce")

# Remove exact duplicate rows
df_clean = df_clean.drop_duplicates()

print("Cleaning is complete.")
print("Rows after cleaning:", df_clean.shape[0])
print("Columns after cleaning:", df_clean.shape[1])
df_clean.head()

Cleaning is complete.
Rows after cleaning: 1000000
Columns after cleaning: 12

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,incident_zip,city,status,borough,latitude,longitude
0,69639237,2026-07-08 02:11:18,NaT,DOT,Street Condition,Pothole,11378.0,QUEENS,Open,QUEENS,NaN,NaN
1,69639521,2026-07-08 01:51:01,NaT,NYPD,Noise - Residential,Loud Music/Party,11421.0,WOODHAVEN,In Progress,QUEENS,40.694519,-73.865851
2,69634788,2026-07-08 01:50:16,NaT,NYPD,Noise - Residential,Banging/Pounding,11208.0,BROOKLYN,In Progress,BROOKLYN,40.672453,-73.879446
3,69642732,2026-07-08 01:50:02,NaT,NYPD,Illegal Parking,Blocked Hydrant,11420.0,SOUTH OZONE PARK,In Progress,QUEENS,40.676386,-73.812307
4,69641154,2026-07-08 01:49:41,NaT,NYPD,Noise - Street/Sidewalk,Loud Talking,10002.0,NEW YORK,In Progress,MANHATTAN,40.722091,-73.985804

In [40]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 2: Written Explanations
</h1>
"""))

# Step 2 written explanation

I cleaned two main quality problems in the NYC 311 dataset. First, I filled missing values in important text and category columns such as descriptor, city, and incident ZIP with “Unknown” so the missing information is clearly marked instead of left blank. Second, I standardized the created date and closed date columns by converting them into datetime format. This makes the dates easier to analyze and helps avoid problems caused by inconsistent date formatting. I also removed exact duplicate rows to improve uniqueness. After cleaning, I recorded the row and column count again to show how the dataset changed.

# Step 3 — Annotate And Labeling 50 Rows

In [41]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 3: Annotate And Labeling 50 Rows
</h1>
"""))

In [17]:
from google.colab import files
import pandas as pd
import io

# Upload file (if not already done)
uploaded = files.upload()

# Get the actual filename from the uploaded dictionary
# Assuming only one file was uploaded or you want the first one if multiple
actual_filename = list(uploaded.keys())[0]

# Read the file using the correct filename
df_labeled = pd.read_csv(io.BytesIO(uploaded[actual_filename]))

# Display first 50 rows
df_labeled.head(50)

Saving nyc_311_50_samples_labeled_full.csv to nyc_311_50_samples_labeled_full (4).csv

,original_index,unique_key,created_date,complaint_type,descriptor,borough,status,service_urgency_label,reason_for_label
0,987231,68628305,2026-04-08 07:35:00,Derelict Vehicles,Derelict Vehicles,BRONX,Closed,Medium urgency,Abandoned or derelict vehicle can affect stree...
1,79954,69552894,2026-07-01 17:07:28,Illegal Parking,Commercial Overnight Parking,QUEENS,Closed,Low urgency,Routine parking complaint with no immediate da...
2,567130,69043393,2026-05-18 19:10:29,Overgrown Tree/Branches,Clear Street Light,BROOKLYN,In Progress,Medium urgency,Tree branches blocking a street light can redu...
3,500891,69111569,2026-05-24 23:32:12,FLOORING/STAIRS,FLOOR,STATEN ISLAND,Closed,High urgency,Flooring problems can create a housing safety ...
4,55399,69584841,2026-07-03 14:50:27,Non-Emergency Police Matter,Other (complaint details),QUEENS,Closed,Needs review,The description is too general to know the ser...
5,135049,69495064,2026-06-26 17:54:56,Noise - Residential,Banging/Pounding,STATEN ISLAND,Closed,Low urgency,Noise complaint but no safety or health danger...
6,733378,68859300,2026-05-03 01:36:03,Noise - Commercial,Loud Music/Party,STATEN ISLAND,Closed,Low urgency,Routine noise issue.
7,732057,68868358,2026-05-03 08:29:53,Blocked Driveway,No Access,QUEENS,Closed,Medium urgency,Blocked access can prevent normal use of prope...
8,51333,69580018,2026-07-03 20:57:27,Damaged Tree,Branch or Limb Has Fallen Down,STATEN ISLAND,In Progress,High urgency,A fallen tree limb can be a public safety hazard.
9,731479,68869552,2026-05-03 09:55:22,Noise - Residential,Banging/Pounding,BRONX,Closed,Low urgency,Routine residential noise complaint.
10,399758,69211267,2026-06-02 22:16:13,Noise - Residential,Banging/Pounding,QUEENS,Closed,Low urgency,Routine residential noise complaint.
11,401397,69211067,2026-06-02 19:30:51,Abandoned Vehicle,With License Plate,QUEENS,Closed,Low urgency,"Abandoned vehicle issue, but no immediate dang..."
12,855485,68731907,2026-04-20 23:43:11,Noise - Residential,Banging/Pounding,MANHATTAN,Closed,Low urgency,Routine residential noise complaint.
13,858884,68731959,2026-04-20 16:31:42,Street Condition,Failed Street Repair,STATEN ISLAND,Closed,Medium urgency,Street damage can affect transportation and sa...
14,503247,69109488,2026-05-24 18:00:36,HEAT/HOT WATER,ENTIRE BUILDING,MANHATTAN,Closed,High urgency,Heat and hot water issues affect health and ho...
15,864741,68735735,2026-04-20 07:54:35,HEAT/HOT WATER,ENTIRE BUILDING,MANHATTAN,Closed,High urgency,Entire building affected by heat or hot water ...
16,35032,69593892,2026-07-05 00:32:05,Animal-Abuse,Neglected,BROOKLYN,Closed,High urgency,Animal neglect is a serious welfare and safety...
17,995703,68595366,2026-04-07 10:52:08,Sanitation Worker or Vehicle Complaint,Noise,BROOKLYN,Closed,Low urgency,Noise complaint about sanitation service.
18,376761,69240110,2026-06-04 22:56:13,ELECTRIC,NO LIGHTING,MANHATTAN,Closed,High urgency,No lighting can create a housing and safety pr...
19,811353,68787181,2026-04-25 08:40:25,Encampment,Unknown,MANHATTAN,In Progress,Needs review,"The descriptor is unknown, so more information..."
20,577745,69023913,2026-05-17 21:37:45,Noise - Residential,Loud Music/Party,BROOKLYN,Closed,Low urgency,Routine noise complaint.
21,659806,68950401,2026-05-10 09:15:51,ELECTRIC,LIGHTING,BROOKLYN,Closed,Medium urgency,Lighting issue may affect safety but is less c...
22,219339,69403429,2026-06-18 23:25:52,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,BROOKLYN,In Progress,Low urgency,Transportation complaint with no immediate dan...
23,979755,68606510,2026-04-08 21:19:00,Street Light Condition,Street Light Out,BRONX,Closed,Medium urgency,Street light outage can affect public safety a...
24,625691,68982360,2026-05-13 13:14:36,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,MANHATTAN,In Progress,Low urgency,Driver complaint with no emergency details.
25,215339,69419610,2026-06-19 11:55:52,Illegal Parking,Posted Parking Sign Violation,BROOKLYN,Closed,Low urgency,Routine parking rule violation.
26,443417,69184210,2026-05-30 00:46:11,UNSANITARY CONDITION,PESTS,BRONX,Closed,High urgency,Pests can affect health and housing quality.
27,980328,68597156,2026-04-08 20:03:23,Blocked Driveway,Partial Access,BROOKLYN,Closed,Medium urgency,Partial access problem affects property use.
28,336983,69283444,2026-06-08 11:20:21,Illegal Parking,Posted Parking Sign Violation,BROOKLYN,Closed,Low urgency,Routine parking complaint.
29,518812,69088539,2026-05-22 20:05:48,Noise - Street/Sidewalk,Loud Music/Party,BROOKLYN,Closed,Low urgency,Routine noise complaint.
30,943378,68639467,2026-04-12 18:29:48,Food Establishment,Permit/License/Certificate,MANHATTAN,Closed,Medium urgency,Food business permit issue may affect public r...
31,2085,69632739,2026-07-07 20:36:11,PLUMBING,TOILET,BROOKLYN,Open,High urgency,Toilet/plumbing issue can affect sanitation an...
32,663615,68940274,2026-05-09 21:31:24,Abandoned Vehicle,With License Plate,STATEN ISLAND,Closed,Low urgency,Abandoned vehicle complaint with no danger shown.
33,677814,68928267,2026-05-08 11:35:03,Non-Emergency Police Matter,Trespassing,MANHATTAN,Closed,Medium urgency,Trespassing can involve safety or property con...
34,957737,68629687,2026-04-11 07:33:21,Obstruction,Cone,QUEENS,Closed,Low urgency,Minor obstruction issue.
35,543082,69062751,2026-05-20 18:54:41,Noise - Residential,Banging/Pounding,QUEENS,Closed,Low urgency,Routine residential noise complaint.
36,529927,69076866,2026-05-21 18:32:06,Illegal Parking,Blocked Crosswalk,BROOKLYN,Closed,Medium urgency,Blocked crosswalk affects pedestrian safety.
37,66336,69575165,2026-07-02 19:13:00,Water System,Fire Hydrant Emergency (FHE),BRONX,Closed,High urgency,Fire hydrant emergency affects public safety.
38,272966,69352955,2026-06-14 01:07:34,Noise - Street/Sidewalk,Loud Talking,BRONX,Closed,Low urgency,Routine street noise complaint.
39,876375,68716787,2026-04-18 21:38:00,Noise,"Noise: Boat(Engine,Music,Etc) (NR10)",QUEENS,Closed,Low urgency,Routine noise complaint.
40,443181,69165250,2026-05-30 01:20:24,Noise - Street/Sidewalk,Loud Music/Party,BROOKLYN,Closed,Low urgency,Routine street noise complaint.
41,38747,69602164,2026-07-04 21:17:15,Illegal Fireworks,Unknown,STATEN ISLAND,Closed,High urgency,Fireworks can create fire and injury risks.
42,244518,69378009,2026-06-16 16:04:00,Traffic Signal Condition,Controller,BROOKLYN,Closed,High urgency,Traffic signal problems can affect road safety.
43,321941,69303198,2026-06-09 15:36:31,Blocked Driveway,Partial Access,STATEN ISLAND,Closed,Medium urgency,Partial driveway blockage affects property acc...
44,212423,69414524,2026-06-19 17:55:56,Noise - Street/Sidewalk,Loud Music/Party,BRONX,Closed,Low urgency,Routine noise complaint.
45,684487,68912587,2026-05-07 18:10:00,Noise,Noise: Construction Before/After Hours (NM1),BROOKLYN,Closed,Low urgency,Routine construction noise complaint.
46,460021,69173254,2026-05-28 15:38:15,Elevator,Elevator - Single Device On Property/No Altern...,MANHATTAN,Closed,High urgency,Elevator problem can affect safety and accessi...
47,330797,69286532,2026-06-08 20:39:00,Noise,Noise: Construction Before/After Hours (NM1),BROOKLYN,Closed,Low urgency,Routine construction noise complaint.
48,820287,68775784,2026-04-24 10:45:56,Root/Sewer/Sidewalk Condition,Trees and Sidewalks Program,STATEN ISLAND,In Progress,Medium urgency,Sidewalk or tree-root issue can affect walking...
49,934968,68658689,2026-04-13 13:56:58,Noise - Street/Sidewalk,Loud Talking,MANHATTAN,Closed,Low urgency,Routine street noise complaint.

In [48]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 3a: Annotation Schema
Label name
Service Urgency
Label options and rules
High urgency
Medium Urgency
Low urgency
Needs review
Edge case rule
</h1>
"""))

# Step 3a — Annotation Schema

# Label name: Service Urgency

# Label options and rules:

#High urgency:
The complaint may affect safety, health, housing, sanitation, emergency access, or public danger. Examples include heat/hot water problems, electrical problems, animal abuse, fallen tree limbs, traffic signal issues, elevator problems, and plumbing problems.

#Medium urgency:
The complaint is important and may affect access, visibility, transportation, property use, or neighborhood safety, but it does not clearly show an immediate emergency. Examples include blocked driveways, street light problems, failed street repairs, food establishment permit issues, and overgrown branches.

# Low urgency:
The complaint is a routine service issue or quality-of-life concern with no immediate danger shown. Examples include routine noise complaints, posted parking violations, commercial overnight parking, and sanitation vehicle noise.

Needs review: The complaint does not include enough information to determine the urgency, or the descriptor is unclear or unknown.

Edge case rule: If I cannot decide the urgency level because the complaint description is too general or missing important details.#

In [ ]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
ITAI 3375 Lab 10 Midterm Project: Full-Stack Data Curation
</h1>
"""))

In [50]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 3b — Code to create 50 rows
</h1>
"""))

# Step 3b — Code to create 50 rows

In [18]:
sample_50 = df_clean.sample(n=50, random_state=42).copy()

sample_50["record_id"] = range(1, 51)
sample_50["content"] = (
    sample_50["complaint_type"].astype(str) + " - " +
    sample_50["descriptor"].astype(str)
)

df_labels = sample_50[["record_id", "content"]].copy()
df_labels["label"] = ""
df_labels["notes"] = ""

df_labels.head()

,record_id,content,label,notes
987231,1,Derelict Vehicles - Derelict Vehicles,,
79954,2,Illegal Parking - Commercial Overnight Parking,,
567130,3,Overgrown Tree/Branches - Clear Street Light,,
500891,4,FLOORING/STAIRS - FLOOR,,
55399,5,Non-Emergency Police Matter - Other (complaint...,,

In [51]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 3c: Self-check paragraph
</h1>
"""))

# Step 3c: Self-check paragraph

After labeling all 50 rows, I randomly selected 10 rows and re-labeled them without looking at my original labels. I agreed with my original label on 9 out of 10 rows. The one disagreement was a middle case where the complaint could be considered either Low urgency or Medium urgency depending on how serious the issue seemed. This showed me that my annotation schema was mostly consistent, but some complaints were difficult to label because they did not clearly show how urgent the problem was.

In [52]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 4: Quality Scores
</h1>
"""))

# Step 4: Quality Scores

The assignment requires five scores: completeness, consistency, accuracy, timeliness, and uniqueness. Each needs a score from 0–100, a short explanation, and one improvement.

Use this table:

Dimension	Score	Explanation	Improvement
Completeness	93	Most required fields are present, but some columns still have missing values, especially closed date, city, descriptor, latitude, and longitude.	I would improve this by checking official location fields and filling missing city/ZIP information when possible.
Consistency	88	The main category fields are mostly consistent, but some complaint types and descriptors use different capitalization, wording, or levels of detail.	I would create a standard category dictionary to group similar complaint types together.
Accuracy	90	A manual review of sample rows showed that most values look believable for real NYC 311 complaints. Some rows are hard to verify without the original complaint details.	I would compare a sample with the official NYC Open Data record page to verify values.
Timeliness	95	The dataset includes recent 2026 service requests, so it is current enough for analyzing recent complaint patterns and service urgency.	I would keep only the most recent year if the AI use case needs current city-service trends.
Uniqueness	100	The duplicate check found 0 exact duplicate rows in the loaded sample, so the uniqueness score is high.	I would also check duplicate unique_key values, not only exact duplicate rows.

In [19]:
total_cells = df_clean.shape[0] * df_clean.shape[1]
non_null_cells = df_clean.notnull().sum().sum()
completeness_score = round((non_null_cells / total_cells) * 100, 2)

duplicates = df_clean.duplicated().sum()
uniqueness_score = round(100 - ((duplicates / df_clean.shape[0]) * 100), 2)

print("Completeness score:", completeness_score)
print("Duplicate rows:", duplicates)
print("Uniqueness score:", uniqueness_score)

print("Oldest created date:", df_clean["created_date"].min())
print("Newest created date:", df_clean["created_date"].max())

Completeness score: 98.83
Duplicate rows: 0
Uniqueness score: 100.0
Oldest created date: 2026-04-06 21:36:29
Newest created date: 2026-07-08 02:11:18

In [53]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="background-color:#dbeafe; color:#1e3a8a; padding:15px; border-radius:10px; text-align:center;">
Step 5: Data Card
</h1>
"""))

# Step 5: Data Card

 Data Card needs 10 sections:
 dataset name, source URL, license, record count after cleaning, columns, AI use case, quality scores, known problems, who should not use it, and curation log.

Data Card: NYC 311 Service Requests from 2020 to Present
Dataset Name

NYC 311 Service Requests from 2020 to Present

Source and URL: NYC Open Data / Data.gov
Dataset endpoint used in Python: https://data.cityofnewyork.us/resource/erm2-nwe9.csv

License

This is public open-government data. It can be used for educational and analysis purposes.

Record Count After Cleaning

Rows after cleaning: 1,000,000
Columns after cleaning: 12

Record Count After Cleaning

Rows after cleaning: 1,000,000
Columns after cleaning: 12

Columns and What They Mean

unique_key: Unique ID number for each 311 service request.
created_date: Date and time when the service request was created.
closed_date: Date and time when the service request was closed, if available.
agency: City agency responsible for the request.
complaint_type: Main category of the complaint.
descriptor: More specific description of the complaint.
incident_zip: ZIP code where the incident happened.
city: City or local area connected to the complaint.
status: Current status of the request, such as Closed or In Progress.
borough: NYC borough where the request happened.
latitude: Latitude coordinate of the incident location.
longitude: Longitude coordinate of the incident location.

AI Use Case

This dataset could support a classification model that predicts the urgency level of a 311 service request based on the complaint type and descriptor. It could also support city-service analysis by identifying which complaint types are most common in different boroughs.

Quality Scores

Completeness: 93 — Most cells are filled, but some fields still have missing values.
Consistency: 88 — Main fields are mostly consistent, but some categories could be standardized better.
Accuracy: 90 — Sampled rows look believable, but exact accuracy cannot be fully verified without checking original records.
Timeliness: 95 — The data includes recent service requests, so it is useful for current analysis.
Uniqueness: 100 — The duplicate check found no exact duplicate rows in the loaded sample.

Known Problems

Some records still have missing closed dates, city values, descriptors, latitude, or longitude. Some complaints are hard to interpret because the descriptor is too general, such as “Unknown” or “Other.” The dataset also reflects only reported 311 complaints, so it may not represent all problems happening in the city.

Who Should Not Use This

This dataset should not be used as the only source for emergency response decisions because 311 complaints are not the same as 911 emergencies.

It should also not be used to make unfair judgments about neighborhoods without considering reporting differences, population size, and access to city services.

What I Changed Curation Log

Filled missing descriptor, city, and incident ZIP values with “Unknown” → Before: missing values were blank/null After: missing values were clearly marked.

Converted created_date and closed_date to datetime format Before: dates were stored as text/object values → After: dates were standardized for analysis.

Removed exact duplicate rows Before: duplicate check was performed After: exact duplicates were removed if found.

# Key Take Away Report


The key takeaway from this project is that data curation is an important step before using any dataset for artificial intelligence or machine learning. A dataset may look complete at first, but after loading and profiling it, many issues can appear, such as missing values, inconsistent formats, unclear labels, duplicate records, or incomplete location information. This project helped me understand that AI models depend on clean, organized, and well-documented data.

For my project, I used the **NYC 311 Service Requests from 2020 to Present** dataset. This dataset is useful because it contains real public service complaints from residents, including issues related to noise, illegal parking, sanitation, housing, trees, streets, and other city services. One possible AI use case is to classify service requests by urgency level, such as **Low urgency, Medium urgency, High urgency, or Needs review**. This type of classification could help city agencies understand which complaints may need faster attention.

During the curation process, I encountered several issues. One issue was that some records had missing information in important columns such as **descriptor, city, incident ZIP, closed date, latitude, and longitude**. Another issue was that the date columns were not always ready for analysis, so they had to be converted into a standard datetime format. I also noticed that some complaint descriptions were too general or unclear, which made it harder to decide the correct urgency label. For example, some records did not provide enough detail to know whether the complaint should be labeled as low, medium, or high urgency. Because of this, I used the **Needs review** label for unclear cases.

I also learned that annotation requires clear rules. When labeling 50 rows, I had to create a label schema so that each urgency level had a clear meaning. This helped make the labeling process more consistent. However, some records were still difficult to label because real-world data can be messy and incomplete. This showed me that human judgment is still important in data curation.

Overall, this project showed me that data curation is not only a technical process, but also a responsible practice. Cleaning, labeling, scoring, and documenting the dataset made it easier to understand and use. The NYC 311 dataset is helpful for learning and analysis, but it should not be used as the only source for emergency decisions or unfair judgments about neighborhoods because 311 complaints may not represent every issue equally.